server.servlet.context-path=/referral_management
spring.application.name=referral_management_Takeshi_Oosihi
server.port=7780
spring.thymeleaf.cache=false

# データベース接続設定
spring.datasource.url=jdbc:mysql://localhost:3306/recruit_management_db
spring.datasource.username=recruit_app_user
spring.datasource.password=**system71
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.messages.basename=messages
spring.messages.encoding=UTF-8